### ISSUE TITLE
Window.Console?

### ISSUE THREAD

**Issue by orsinium** [gowebapi/webapi#10]
How to call `console.log`? We definitely need a good old debugger ;)

**Comment by martin-juhlin** [comment]
The [console specification](https://console.spec.whatwg.org/#console-namespace) is using namespaces that isn't supported by the binding program, see gowebapi/webidl-bind#5. 

The specification is also using type _any_ that is translated into _js.Value_ that is hard to use. Any suggestion on how a good _console.log_ api should look like in Go?

**Comment by orsinium** [comment]
`interface{}` works perfectly for type `Any` :)

**Comment by orsinium** [comment]
```go
func (window Window) Console() Console {...}
func (console Console) Log(args ...interface{}) {...}
```

**Comment by janpfeifer** [comment]
This is an old issue, but just in case: to write to the console from Go you can simply `fmt.Printf()` your content. Does that solve the issue for you ? 

Btw, things like `github.com/golang/glog` work as well if one redirects the output to stderr (with `flag.Set("logtostderr", "true")`), and will output to the console in WASM.

**Comment by orsinium** [comment]
That's an old issue indeed. Now I use my own [gweb](https://github.com/life4/gweb), it has the good old [Window.Console.Log](https://github.com/life4/gweb/blob/master/web/console.go#L19). Sorry for bothering you.

**Comment by janpfeifer** [comment]
Thanks for the pointer, I'll give gweb a try!
