### ISSUE TITLE
Example_buttonTest() in example_test.go panics when button is clicked

### ISSUE THREAD

**Issue by smoyer64** [gowebapi/webapi#14]
Tested in both FF 83 and Chromium 86 with the following Go environment:

```(text)
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/smoyer1/.cache/go-build"
GOENV="/home/smoyer1/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/smoyer1/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/smoyer1/go:/usr/share/go-tools"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go/1.15.4"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/1.15.4/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/smoyer1/git/hnjobs/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build286617590=/tmp/go-build -gno-record-gcc-switches"
```

Compiled with:

```(text)
RUN GOOS=js GOARCH=wasm go build -o /app cmd/ui/ui.go
```

The console provides the following call stack when the button is clicked:

```(text)
panic: ValueOf: invalid value wasm_exec.js:50:14
<empty string> wasm_exec.js:50:14
goroutine 6 [running]: wasm_exec.js:50:14
syscall/js.ValueOf(0x1e5e0, 0x5ab88, 0x6, 0x7ff800010000000f) wasm_exec.js:50:14
	/usr/local/go/src/syscall/js/js.go:219 +0x106 wasm_exec.js:50:14
syscall/js.Value.Set(0x7ff8000100000012, 0x41a078, 0x52ef6, 0x6, 0x1e5e0, 0x5ab88) wasm_exec.js:50:14
	/usr/local/go/src/syscall/js/js.go:314 +0x7 wasm_exec.js:50:14
syscall/js.handleEvent() wasm_exec.js:50:14
	/usr/local/go/src/syscall/js/func.go:97 +0x25
```

I'd be happy to help track this down ... it appears that the JS value passed to the `syscall/js` `ValueOf()` function is perhaps a wrapped type and doesn't match any of the types in the case statement included there (see https://github.com/golang/go/blob/0e953add9656c32a788e06438cd7b533e968b7f8/src/syscall/js/js.go#L162).  I've looked through the webapi code and all the JS values appear to (properly) be aliases which I would expect to match a case, so I'm at a loss for where to continue looking.

**Comment by smoyer64** [comment]
Retrieving the button and turning it into the typed DOM element works fine (which I kind of suspected since the panic occurs when the button is actually clicked.  Using the "low-level" `syscall/js` methods to create the handler works as in:

```(go)
	bar := webapi.GetWindow().Document().GetElementById("bar").JSValue()
	bcount := 0

	cb := js.FuncOf(func(this js.Value, args []js.Value) interface{} {
		bcount++
		this.Set("textContent", fmt.Sprintf("I am clicked %d time", bcount))
		return nil
	})
	bar.Call("addEventListener", "click", cb)
```

**Comment by smoyer64** [comment]
Another clue is that the handler actually executes the instructions in it's body ... the panic seems to happen somewhere in the return process.  A `js.Func()` normally has a `interface{}` return signature so perhaps the non-working version above is having a problem dealing with the return value?

**Comment by smoyer64** [comment]
The `eventFuncHTMLElement_htmlevent_MouseEvent` function in `html/html.go` returns the `js.Undefined` function.  In `syscall/js/js.go` panics because the undefined type isn't in its case statement.  I think this is an error in the `syscall/js` library but I'd like opinions.

**Comment by martin-juhlin** [comment]
Now I'm not really following. `eventFuncHTMLElement_htmlevent_MouseEvent` is return a `js.Func`. I don't see how that can end up with a `js.Undefined`.
The low level code above doesn't match the example. May be the example works better with AddEventClick (I haven't tested)?

**Comment by smoyer64** [comment]
That's the closure ... when the button is clicked, it's the enclosed function that's executed and it returns `js.Undefined`:

```(go)
func eventFuncHTMLElement_htmlevent_MouseEvent(listener func(event *htmlevent.MouseEvent, target *HTMLElement)) js.Func {
	fn := func(this js.Value, args []js.Value) interface{} {
		var ret *htmlevent.MouseEvent
		value := args[0]
		incoming := value.Get("target")
		ret = htmlevent.MouseEventFromJS(value)
		src := HTMLElementFromJS(incoming)
		listener(ret, src)
		return js.Undefined
	}
	return js.FuncOf(fn)
}
```

Looking through the `syscall/js` code in Go, I get the impression we should be adopting Go semantics here and that they're expecting us to return `nil` but that has a different semantic meaning right?

I've also an issue in the Go issue tracker: https://github.com/golang/go/issues/42523

**Comment by smoyer64** [comment]
Here's a link to the specification: https://dom.spec.whatwg.org/#interface-eventtarget.  Under the covers, the specification says that the `handleEvent(evt)` method returns `undefined` which is why I'm leaning towards the Go behavior being wrong.  Adding undefined to `ValueOf()` in the Go code fixes this problem in a better way but I'll wait to see what they say.

**Comment by martin-juhlin** [comment]
I think it's wrong in the generated code above. The method is returning js.Undefined, the function, not js.Undefined() that is js.Value. right?

**Comment by smoyer64** [comment]
Hmm ... I believe that's correct ... the closure should return the function that `handleEvent()` executes and the enclosed function should provide something that becomes `result`.  I still think that this might panic in `syscall/js.ValueOf()` though.

**Comment by smoyer64** [comment]
That fix is confirmed ... I knew this was going to need to be applied to all the event listeners and I see that the generator(s) did the bulk of the work!  Thanks so much.

As a follow up, `syscall/js.ValueOf()` actually recurses on `js.Undefined` (well ... the unexported underlying `js.Value`) so it doesn't panic be rather ends up setting `result` to 0.  I'm still not sure this is the correct behavior given the specification but I'm happy to see that it's working.

**Comment by martin-juhlin** [comment]
Thank for the help! :-)
