### ISSUE TITLE
How to use indexeddb?

### ISSUE THREAD

**Issue by ghost** [gowebapi/webapi#2]
Would you mind to create an example how to use indexeddb?
I managed to open a db request but have no clue to get db instance from event like below.
`request := webapi.GetWindow().IndexedDB().Open("test", nil)`
`request.SetOnupgradeneeded(domcore.EventHandlerToJS(func(event *domcore.Event) interface{} {`
`   /* javascript version is:`
`     var db = event.target.result;`
`     var objStore = db.createObjectStore("names", { autoIncrement : true });`
`   */`
`    return nil`
`}))`
`

**Comment by martin-juhlin** [comment]
Hi, sorry for the late response. In specification, example 1 is using "request.result" instead of "event.target.result". try following:
```
	db := indexeddb.IDBDatabaseFromJS(request.Result())
	db.CreateObjectStore("names", &indexeddb.IDBObjectStoreParameters{
		AutoIncrement: true,
	})
```
