### ISSUE TITLE
Canvas 2D context

### ISSUE THREAD

**Issue by orsinium** [gowebapi/webapi#7]
I see `graphics/webgl` for `webgl` canvas context but can't find [CanvasRenderingContext2D](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D). Is it generated?

**Comment by martin-juhlin** [comment]
Yes, according to the [cross reference index](https://gowebapi.github.io/jscrossref/) it is located in [html.canvas](https://godoc.org/github.com/gowebapi/webapi/html/canvas#CanvasRenderingContext2D) package.
